### ISSUE TITLE
On Start: SysRecipe not valid fault

### ISSUE THREAD

**Issue by dc3nity** [hyc-sg/Helios-public#11]
**Machine ID**
ALL (PLC V2.12)

**Describe the bug**
On start, SysRecipe not valid fault always present

**To Reproduce**
1. Full shutdown of PLC
2. Restart PLC, wait for HMI to load
3. Fault present

**Expected behavior**
No faults

**Images or Screenshots**
Please try to capture images or screenshots of the bug for better understanding and resolution.

**Additional context**

**Comment by HycAlex** [comment]
to force user (operator) to download recipe to ensure proper data is loaded to PLC for operation.
