### ISSUE TITLE
Heating Fault bug

### ISSUE THREAD

**Issue by simchu** [hyc-sg/Helios-public#12]
**Machine ID**
SA034

**Describe the bug**
Zone 6 temperature higher then set temperature PLC control the power not on and got heating fault

**To Reproduce**
1. Go to 'Main Page'
2. Click on 'Select recipe Yuma Power Bowl. Turn on heater and run overnight'
3. Run at 0 ft/min
4. Bug present after zone 6 heated up more than SV125 which is 136 continuously. the fault appear.

**Expected behavior**
Zone 6 heated up more than SV125 which is 136 continuously. the fault appear.

**Images or Screenshots**
Please try to capture images or screenshots of the bug for better understanding and resolution.
![image](https://user-images.githubusercontent.com/108838085/177649532-1e0468eb-e816-4f3b-9300-a1237878720b.png)

**Additional context**
MCB doesn't trip

**Comment by HYC-Alice** [comment]
With Issue #13: Beckhoff has no solution to this issue yet. Requesting for their presence on-site.

**Comment by HycAlex** [comment]
Zone 6 set point is 125 which is 40 degree below zone 5(165) and same value at zone 7(125). at statics condition (conveyor at rest) heat distribute from zone 7 gradually rise to zone 5 and thus not possible to control zone 6 temperature same set point as zone 7 and 40 degree below zone 6. 
Nothing to do with beckhff, this is physics
