### ISSUE TITLE
CIP: To Allow user to write motor speed offset to XML file

### ISSUE THREAD

**Issue by HycAlex** [hyc-sg/Helios-public#14]
**Machine ID**
Alpha model

**Describe the bug**
CIP

**To Reproduce**
CIP

**Expected behavior**
1. Only allow Engineer level to save the motor speed offset back to xml file
2. FSE to report the change with the new XML file back to SG

**Images or Screenshots**

**Additional context**

**Comment by enzo-hycsg** [comment]
Release on v3.2
