### ISSUE TITLE
CIP: To save the TC para to XML file

### ISSUE THREAD

**Issue by HycAlex** [hyc-sg/Helios-public#15]
**Machine ID**
Alpha

**Describe the bug**
CIP

**To Reproduce**
CIP

**Expected behavior**
1. When new TC is replaced
2. User to input the TC para - Gradient and y-intercept to HMI and then save the para to TCCalData.XML
3. FSE to report with new XML file to SG

**Images or Screenshots**
Please try to capture images or screenshots of the bug for better understanding and resolution.

**Additional context**

**Comment by enzo-hycsg** [comment]
Release on v3.2
