### ISSUE TITLE
CIP: Upper conveyor inverter overcurrent 

### ISSUE THREAD

**Issue by HycAlex** [hyc-sg/Helios-public#17]
**Machine ID**
SA032

**Describe the bug**
when the lower conveyor motor is de-coupled, upper conveyor inverter burnt or MCB trip, suspect over current (Reported by Toh)

**To Reproduce**

**Expected behavior**
1. Inverter should fault out when there is over current, to verify inverter over current setting
2. PLC fault out if the encoder feedback is too far from the set speed

**Images or Screenshots**

**Additional context**

**Comment by enzo-hycsg** [comment]
KIV, fanning-out parameter settings to other inverters
