### ISSUE TITLE
CIP: Retentive Timer

### ISSUE THREAD

**Issue by HycAlex** [hyc-sg/Helios-public#18]
**Machine ID**
Alpha

**Describe the bug**
CIP: Function block of Retentive timer

**To Reproduce**
CIP

**Expected behavior**
1. To keep count of current enabled duration
2. To add the current enabled duration to last saved duration
3. To save the total enabled duration and reload upon re-power up
4. Reset input to clear all data

**Images or Screenshots**
<img width="216" alt="image" src="https://user-images.githubusercontent.com/103486093/190340084-5fb7a827-6014-47ff-9fb2-1579b8b8c1cf.png">

**Additional context**

**Comment by HycAlex** [comment]
to counting time counting upon re-power up

**Comment by enzo-hycsg** [comment]
KIV
