### ISSUE TITLE
REQ(D): Motion Speed Offset Range

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#19]
**Machine ID**
SA031 and for rest of alpha systems

**Describe the bug**
On 8 Sep, we changed the offsets for RS due to observed high current, loud sounds and waves. FP Gavin has requested us to conduct a motion DOE to create ranges for conveyor motion to be able to tell tool health, how much adjustment to make for speed offset.

**To Reproduce**

**Expected behavior**
1. A range of acceptable speed offsets adjustments WI 
2. When to change offsets/jackshafts; What would be the expected outcome if a certain offset was adjusted.. What to look out for, what motor to adjust.

**Images or Screenshots**

**Additional context**
Per Gavin's request: All offset changes need to request permissions from FP. And only level 3 trained/HYC Control Personnel should be able to change the offsets.

**Comment by enzo-hycsg** [comment]
Any update on this?

**Comment by HYC-Alice** [comment]
> Any update on this?

Compiled the alpha systems current offsets for all speed.
As of now, we only recently changed SA031's 60fpm and 105fpm RS offsets.
Then yesterday (8Nov), we changed SA035's LS 30fpm offsets. 
Still monitoring, but am working on WI.
