### ISSUE TITLE
Interlocking between auto-run and jog mode

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#2]
Both mode overlapped. One silo would be on auto-run, but then the other is stop and working on jog mode.

**Comment by xalicelau** [comment]
Might affect the belt

**Comment by dc3nity** [comment]
work required:

- [x] identify issue
- [ ] propose solution
- [ ] implement solution

**Comment by enzo-hycsg** [comment]
This has been solved internally. It will be part of the R2.12 software release.

**Comment by enzo-hycsg** [comment]
Oven Software R2.12 was released to customer, this issue was addressed in this version.
