### ISSUE TITLE
REQ(D): IR heater rod reduction DOE

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#20]
**Machine ID**
SA031

**Describe the bug**
FP Gavin requested IR heater rod reduction DOE (to define recipe, may be pull fuse out to know how many heater boxes are sufficient for oven operation). 

**To Reproduce**

**Expected behavior**

**Images or Screenshots**

**Additional context**

**Comment by enzo-hycsg** [comment]
Any update on this?

**Comment by HYC-Alice** [comment]
SA035(with old heater box design) is currently being compared to SA034 (with new upgraded heater boxes in Zone 9, H4A, and H5A). 
No updates from FP side.
