### ISSUE TITLE
REQ(D): PTFE DOE documentation

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#21]
**Machine ID**
SA031

**Describe the bug**
FP Gavin is requesting for range of acceptable current ampere per speed and update on PTFE usage.
Todd requested two different dispensing and delay time per silo.

**To Reproduce**

**Expected behavior**

**Images or Screenshots**

**Additional context**
FP Alicia noticed that after we add in more PTFE to the dispenser...Within the 1st hour, the bowls would have PTFE, but a few hours later it wouldn't have any PTFE on them.

**Comment by enzo-hycsg** [comment]
Any update on this?

**Comment by HYC-Alice** [comment]
> Any update on this?

No update on this. We are also waiting on SG side's PTFE DOE test results.
