### ISSUE TITLE
Drum Encoder Fault did not stop the drum

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#22]
**Machine ID**
SA035

**Describe the bug**
6Sep: Encountered LS Drum Encoder Fault message on SA035. Machine did not stop. Found LS infeed coupling opened, and drum encoder disc shifted down.

18Sep: RS drum encoder sensor feedback fault, light is too weak, it could be dirty or may need to adjust the sensitivity.

**To Reproduce**

**Expected behavior**
We want the oven to stop.

**Images or Screenshots**
![image](https://user-images.githubusercontent.com/103921122/191349023-1fb016ef-b3bf-46d1-922c-7936bab95911.png)
![image](https://user-images.githubusercontent.com/103921122/191348664-9abe35d8-9941-4436-af06-062bd13984ad.png)
![image](https://user-images.githubusercontent.com/103921122/191348067-25aec796-4cf1-47b0-a37b-1b702c6a2eb1.png)

**Additional context**

**Comment by enzo-hycsg** [comment]
This is a valid bug. Bug fix to be release on v3.2, WW42.5

**Comment by enzo-hycsg** [comment]
For software release v3.2, WW42.5

**Comment by enzo-hycsg** [comment]
Release on v3.2
