### ISSUE TITLE
28Sep SA035 Jogmode showed fault message

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#25]
**Machine ID**
SA035

**Describe the bug**
Jogmode showed fault message despite already reset before going into jogmode.

**To Reproduce**

**Expected behavior**
Jogmode shouldn't have any event logging?

**Images or Screenshots**
![image](https://user-images.githubusercontent.com/103921122/193107403-dc5dda6b-e31b-4f4a-bc5f-9ec9dbf28bd5.png)

**Additional context**
This happened as we were troubleshooting SA035 RS lower conveyor encoder fault and RS drum encoder fault.
After we put back #1 and #2 wires (forward/reverse) in the right silo inverter in control box.

**Comment by enzo-hycsg** [comment]
Encoder Fault only happens while Run/Reverse output is On and Encoder has no signal (No Pulse),  The user might have unknowingly pressed the Run button which activates Run/Reverse output.
