### ISSUE TITLE
28Sep SA031 machine did not stop despite drum current critical fault and 18A

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#26]
**Machine ID**
SA031

**Describe the bug**
After replacing RS curved chainrunner, the drum current went up to 18A but the machine is still running despite drum current critical fault. After loosening the jackshafts, the current went back to normal. 

**To Reproduce**

**Expected behavior**

**Images or Screenshots**
Please try to capture images or screenshots of the bug for better understanding and resolution.

**Additional context**

**Comment by enzo-hycsg** [comment]
This is a valid bug, bug fix for release on WW42.5

**Comment by enzo-hycsg** [comment]
Release on v3.2
