### ISSUE TITLE
29Sep SA031 Jogmode RS Forward felt like it's going backwards

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#27]
**Machine ID**
SA031

**Describe the bug**
When running jogmode with all 3 motors selected, RS forward gave a feeling that no belt was pulled and the belt would jog backwards at RUC at 6hz. Changed to 8hz and then back to normal 30fpm and it's back to normal

**To Reproduce**

**Expected behavior**
Expected jogmode to go forward

**Images or Screenshots**

**Additional context**

**Comment by enzo-hycsg** [comment]
This is normal as we are operating the motor in a very low speed resulting to low torque, the conveyor tension might be tight. Increasing the speed will solve this.
