### ISSUE TITLE
SA036's event log and alarm log are mismatch again for log9

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#28]
**Machine ID**
SA036

**Describe the bug**
SA036's event log and alarm log are mismatch again for log9.

**To Reproduce**
1. Go to Oven-->Log
2. Click on Alarm Log/Event Log folder and look at Log 9
![image](https://user-images.githubusercontent.com/103921122/195003542-abd8bec7-823c-435e-9299-d5caa07eb756.png)

**Expected behavior**
Expected Log 9's event log/alarm log to not have any log as the machine wasn't running/touched on 9Oct.

**Images or Screenshots**
Log9 has log 10’s log(alarm)
![image](https://user-images.githubusercontent.com/103921122/195003205-a81dc1f6-888f-40dd-a204-b42defa6e632.png)

Then log10 is like this (alarm)
![image](https://user-images.githubusercontent.com/103921122/195003247-d4515c92-ea5c-48fc-8afe-c81a57e06067.png)

Event is the same issue.. log 10 events for log 9..
![image](https://user-images.githubusercontent.com/103921122/195003271-3533d0f7-3cb4-4fe9-a3c4-4ee0b93837bb.png)

Log10's event log didn’t have headers
![image](https://user-images.githubusercontent.com/103921122/195003332-d0dc03ce-8ace-4aab-aadc-ac8b091ebacd.png)

**Additional context**
There wasn’t any shutdown. The machine was just not running at all yesterday (9Oct), then the log happened when we ran the machine today (10Oct)

**Comment by enzo-hycsg** [comment]
This is a valid bug. Issue will be escalated to Beckhoff, the issue is related to "Logged day" logger inputs. The function block manage it's own logged day based on system date and time.

**Comment by enzo-hycsg** [comment]
Closed and keeping in view this bug as BECKHOFF did not find any errors on our code. We'll reopen once we have critical occurrences of this bug.
