### ISSUE TITLE
CIP: OEE improvements

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#29]
**Machine ID**
SA031/Alpha systems-OEE

**Describe the bug**
FP Keyla: Is there a way to be able to see the graph from like previous days like not yesterday/today (like the graphs on the HMI).  
FP Alicia: Maybe have buttons to change settings instead of a drop down list so that it is simpler and quicker to change OEE modes.

**To Reproduce**

**Expected behavior**

**Images or Screenshots**

**Additional context**

**Comment by enzo-hycsg** [comment]
Closing this request as there is a separate OEE improvements being discussed separately with Gavin.
