### ISSUE TITLE
CIP: Heater health runtime

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#30]
**Machine ID**
SA031/Alpha system

**Describe the bug**
Currently, the heater runtime still records even if we disconnected the heaters. Was wondering if we can come up with something to stop the runtime for the specific heater that was disconnected.
 
Enzo: Our heater current detection is per Phase, it can check a heater fault/disconnected on that Phase but it doesn’t know which Heater. Probably add a checkbox or a button to inform the plc that a particular heater is disconnected?

**To Reproduce**

**Expected behavior**

**Images or Screenshots**
Please try to capture images or screenshots of the bug for better understanding and resolution.

**Additional context**

**Comment by enzo-hycsg** [comment]
This request is addressed in version 3.3 which will be release on WW50
