### ISSUE TITLE
SA036-Heater Health (Ampere Reading) is a bit faulty on HMI

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#31]
**Machine ID**
SA036

**Describe the bug**
SA036 has two faulty heaters with their fuse being lifted up.
H21, H41(heater fuse burnt), but on the HMI it’s not showing that it’s faulty. 
For H21, the HMI ampere reading showed ~26A (which is in the +/-2A range), thus I can see why it's not "red" on the HMI. 
For H41, we have a heater fuse burnt, and the HMI ampere reading showed ~24A and you can see the number of "heaters" counter on the HMI is at 3 heaters, but still doesn't light up red. 

**To Reproduce**
1. Go to Conveyor and Heater Runtime, force on all heaters
2. Check control box ampere reading as well

**Expected behavior**
Expected H21, H41 to have a red fill. 

**Images or Screenshots**
![9nov-SA036 heater health hmi ](https://user-images.githubusercontent.com/103921122/200960830-ae94ba50-1fd7-4181-aba7-4ccffc1a6ed5.png)

![image](https://user-images.githubusercontent.com/103921122/200960878-9ab5728e-db1c-4ba4-bff2-7daea0a8f386.png)

**Additional context**

Happened before V3.2 upgrade. And is also still happening

**Comment by enzo-hycsg** [comment]
Try swapping CT or EL3446 cards, it's likely a hardware issue.

**Comment by HYC-Alice** [comment]
Update: MX4 site FSE personnel conducted some tests with CT, came to the conclusion that will need to change EL3446 cards.
