### ISSUE TITLE
31Oct: SA036 conveyor runtime and heater runtime restarted after replacing Z5 SSR

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#32]
**Machine ID**
SA036

**Describe the bug**
 SA036 conveyor runtime and heater runtime restarted after replacing Z5 SSR. It didn't record the "last cleared" as well.

**To Reproduce**
1. Replace SSR 
2. Restart machine

**Expected behavior**
SA036 conveyor runtime and heater runtime shouldn't be cleared/reset. Should still have data since Sep 9th.

**Images or Screenshots**
Please try to capture images or screenshots of the bug for better understanding and resolution.

31Oct: 8:38 am before SSR Z5 replacement 
![31oct_runtime at 838am](https://user-images.githubusercontent.com/103921122/200962815-7a6031ea-620d-49fc-8a20-83111e0a19ee.jpeg)

31Oct: 10:30am after SSR Z5 replacement
![31oct_runtime at 1030am after SSR Z5](https://user-images.githubusercontent.com/103921122/200962871-28d8bb0a-d874-436b-a04e-809962cac01d.jpeg)

**Additional context**

![image](https://user-images.githubusercontent.com/103921122/200963512-6b3cdfc0-78b9-4dd4-a44d-b9b179d3f5e4.png)

![image](https://user-images.githubusercontent.com/103921122/200963526-fe6cc5b3-1820-482d-841a-4e0125520cc8.png)
![image](https://user-images.githubusercontent.com/103921122/200963565-7388be37-fd73-41ee-a45e-9178060f5ea1.png)

**Comment by HYC-Alice** [comment]
Updated on 8Nov: Conveyor and heater runtime were edited. So it included the time since Sep 9th.
![image](https://user-images.githubusercontent.com/103921122/200963356-f3bbc723-0907-4dee-bd49-6f76c58eb9d3.png)

**Comment by enzo-hycsg** [comment]
This is WritePersistent data function bug where we can't control... data corruption is common to PC like controllers during a sudden shutdown. Counter protection are already in place, runtime data is being log hourly for traceability such as this, a special data backup function is also in place wherein data is being written into memory within 1 second during a sudden shutdown, this function only works if the IPC battery is ok. Ultimately, always practice to properly shutdown the IPC.
