### ISSUE TITLE
CIP: Adding another password for "Expert Use"

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#33]
**Machine ID**
SA031/ All alpha or future software 

**Describe the bug**
FP Gavin say he wants to keep expert use only locked under another password as he doesn't want the offsets to be easily touched by others. 

**To Reproduce**
Login as Engineer

**Expected behavior**

**Images or Screenshots**
![image](https://user-images.githubusercontent.com/103921122/203184223-036ca937-1981-4abb-8b43-904db2ccd4e0.png)

**Additional context**

**Comment by enzo-hycsg** [comment]
This feature will be accessible through "Admin" user only.

**Comment by dc3nity** [comment]
@enzo-hycsg to confirm, this will be visible for all users, but grey out and no interaction for any users except admin users?

**Comment by enzo-hycsg** [comment]
Yes correct.. :)

**Comment by dc3nity** [comment]
Updated and plan release for ER5
