### ISSUE TITLE
3Dec: SA032 Wrong fault message

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#34]
**Machine ID**
SA032

**Describe the bug**
On 3Dec, 10:12am, encountered  "Lower Conveyor Encoder Feedback Fault" (even though there wasn't any issues on Lower conveyor encoder) instead of drum coupling loosened at SA032.

**To Reproduce**
Need to verify again by unplugging the encoder connector intentionally -->To follow up with Emerson

**Expected behavior**
Expected Drum Encoder Feedback Fault

**Images or Screenshots**
![image](https://user-images.githubusercontent.com/103921122/208280372-85cba033-13a8-4967-a571-e890d5a758bd.png)
![image](https://user-images.githubusercontent.com/103921122/208280376-bad7f7bc-fcf2-404d-90b0-4c68ee3c5adf.png)

**Additional context**

**Comment by enzo-hycsg** [comment]
Verified, the Fault Message is correct according to Encoder.
