### ISSUE TITLE
Wrong tooltip info for 105FPM start button

### ISSUE THREAD

**Issue by dc3nity** [hyc-sg/Helios-public#35]
**Machine ID**
ALL ALPHA SERIES

**Describe the bug**
105fpm start button tooltip displays as 120fpm start instead of 105fpm

**To Reproduce**
1. Reset and ready the machine
2. Mouse over (do not click) 120fpm start
3. "Conveyor Start @ 120fpm" displayed

**Expected behavior**
"Conveyor Start @ 105fpm"

**Images or Screenshots**
Please try to capture images or screenshots of the bug for better understanding and resolution.

**Additional context**

**Comment by dc3nity** [comment]
@enzo-hycsg request to self-assign and resolve in 3.4

**Comment by enzo-hycsg** [comment]
@dc3nity how is this? I prefer to remove the tooltip text for object that are self-explanatory or has a name on it. Let's use tooltip text where object has abbreviated text or difficult to understand.

**Comment by dc3nity** [comment]
fixed in ER5
