### ISSUE TITLE
20Dec: SA032 Faulty reading for all phases in Zone 8

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#36]
**Machine ID**
SA032

**Describe the bug**
Discovered a faulty reading for all phases in Zone 8 at SA032. 

**To Reproduce**
1. Login to engineer mode
2. Click on '!'
3. Turn heaters on 
4. Bug present

**Expected behavior**
The heater counter should only have "4" 

**Images or Screenshots**
![image](https://user-images.githubusercontent.com/103921122/208782173-01837e61-01bb-4526-86d6-0d44380d8aab.png)
![image](https://user-images.githubusercontent.com/103921122/208782206-ac5f548c-3218-459f-97a2-1ba0880edc16.png)
![image](https://user-images.githubusercontent.com/103921122/208782138-79e4d374-164a-4843-b9ff-8d5cd877dd77.png)

**Additional context**

**Comment by enzo-hycsg** [comment]
@HYC-Alice this is likely a hardware issue, how the reading right now?

**Comment by enzo-hycsg** [comment]
@HYC-Alice just checking in on the status of this, has this been rolled out as hardware issue?
