### ISSUE TITLE
25Jan'23: SA031 PTFE timer internal twincat bug

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#44]
**Machine ID**
SA031

**Describe the bug**

1. First dispense at 09:09am (60fpm)
2. Second dispense at 17:09pm.

A duration of 8 hours. 

From the time I have checked the delay timer (around 2:38pm) ...it did dispense after "5 hours".
Unsure about the previous dispense timer. Will monitor on this again.

Temporary conclusion: Looks like it's an internal twincat bug, the timer is supposedly working while IN is TRUE and it has not reached the target time.  

**To Reproduce**
3. Run at ...
4. Bug present

**Expected behavior**
PTFE to dispense again after 5 hours 

**Images or Screenshots**
Please try to capture images or screenshots of the bug for better understanding and resolution.

**Additional context**

Dispensed around 9:09am
Per Osbaldo, did not see any dispense happen before 12:45pm
2:38pm: After Jerry notified that there’s no sign of dispense (since 5 hours from 9:09am should be around 2sth pm)
I found that the delay time was still at 2hr 28min (so it technically "dispensed" again around 11sth am)
![image](https://user-images.githubusercontent.com/103921122/214734530-ba734436-011d-4df3-80c1-f37ee7310e38.png)

Conveyor stopped at 17:31
Delay timer stopped at 3m16s37 with motion off

**Comment by enzo-hycsg** [comment]
KIV
