### ISSUE TITLE
3May: Can't go to manual page/logout after logging in.

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#5]
![can't go to manual or logout](https://user-images.githubusercontent.com/103921122/166970674-551f28b0-5140-49e3-b69d-d5ec47e3ea51.jpeg)

**Comment by enzo-hycsg** [comment]
This is not a bug. Our software is preventing user from logging out while oven is in production state (motion is running and all zone temperature are in green. Move away from production state by stopping the heaters or the motors.
