### ISSUE TITLE
5May: Slow pickup to 30fpm

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#6]
Did reverse, and then stopped jogmode and then ran 30fpm on PLC, but PLC is slow on ramping up the speed to 30fpm. 
Suspect: Jogmode needs to be completely closed/on main screen on all before able to fully run on 30fpm.
![slow pickup to 30fpm](https://user-images.githubusercontent.com/103921122/166971143-ffecc831-6eeb-4984-a9d2-dee150010970.jpg)

**Comment by enzo-hycsg** [comment]
This is not a bug. We need to stop using the external laptop and only use the oven PC UI. The disabled manual button but in green color indicates that the either the laptop or the oven PC is in manual page or jog screen is opened, jog speed is being forced into motor speed variable.
