### ISSUE TITLE
16May: Inverter log: file not found

### ISSUE THREAD

**Issue by HYC-Alice** [hyc-sg/Helios-public#8]
**Machine ID**
SA031

**Describe the bug**
The inverter log data for May 12th-May 16th are missing. 

**To Reproduce**
1. Go to FB_InverterDataLog and put enable to false.

**Expected behavior**
We expect that the inverter data log would record the file and we would be able to access it regardless of the time we open up the data.

**Images or Screenshots**
Can't find the inverter data from May 12th-today. Encountered error with 1804
![image](https://user-images.githubusercontent.com/103921122/168732402-7b46abed-1bfa-4293-91b4-d9858238c431.png)

**Additional context**
Was able to reset it by manually enabling it. Have data for May 16th 9:44am onwards.

**Comment by enzo-hycsg** [comment]
Bug acknowledge. I'm working on this...

**Comment by enzo-hycsg** [comment]
Beckhoff can't replicate this bug. To address this, a containment was implemented in version 2.12, if an error is detected,  the function block will disabled and then auto enabled.
