### ISSUE TITLE
Visu Logout Error

### ISSUE THREAD

**Issue by dc3nity** [hyc-sg/Helios-public#9]
**Machine ID**
SA031

**Describe the bug**
After login to "Engineer" account and using for awhile, logout button is unresponsive

**To Reproduce**
1. Login to "Engineer" account
2. Click on gear icon to view motor performance
3. Close window
4. Click on logout button

**Expected behavior**
Logout of Engineer account

**Images or Screenshots**
![image](https://user-images.githubusercontent.com/100349011/174143649-fe59b50b-6b7f-40fb-b8a0-3aee09bff36b.png)

**Additional context**

**Comment by enzo-hycsg** [comment]
The above issue is not a bug... its part of log-in/logout interlock wherein log-in/logout is disabled when oven is in production mode (all zone temperature are within the setpoint). To log-out, off the heaters and/or stop the motion.

**Comment by HycAlex** [comment]
Closed
